// ── campaigns: spend riff tokens to put a catalogue track in front of
//    people, billed by attention rather than by the clock ──────────────
//
//   POST /api/promote          { wallet, url, credits, modes, label }
//   GET  /api/promotions       → the live campaigns, for display only
//   GET  /api/promotions/next  → one campaign to show, one credit spent
//   POST /api/promo/event      → engagement, never money
//   GET  /api/promotions/mine  → the owner's own numbers
//   POST /api/promotion/action → pause, resume, add credits
//
// One credit = one person's attention. riffrolled does not promise a
// play, only the chance of one, so the billable moment is the one thing
// it controls: showing the card. That is why the serve endpoint is the
// only place a balance moves, and why /api/promo/event can be called a
// million times without costing anybody a credit.
//
// Only tracks already in the shared catalogue can be promoted, so the
// promoted strip can never carry arbitrary content — same safety story
// as the rest of the site.

import { json, errorJson, readJson, nowIso } from '../utils/response.js';
import { getConfig } from '../config.js';
import { parseTags, tagScore } from '../tags.js';
import {
  WALLET_RE, canonicalYouTubeUrl, getTrackByUrl,
  walletBalance, addLedger, ensureWallet,
  walletPromotions, getOwnedPromotion, pausePromotion, resumePromotion,
  // campaigns / consumption billing
  livePromotions, spendCredit, bumpCampaignStat, liveCampaignFor,
  addCredits, addCampaign,
  // AI brief placements
  aiCampaignPool, offerBriefCandidate, unchargedOffers, claimBriefOffer,
  pruneBriefOffers, setCampaignTags,
} from '../db/queries.js';

/* A brief id is generated by the browser and is the only thing tying a
   copy back to the campaigns that were offered. Narrow on purpose: it
   goes straight into a keyed lookup, and anything that is not 32 hex
   characters is a client bug or someone poking at the endpoint. */
const BRIEF_RE = /^[0-9a-f]{32}$/;

export async function handlePromote(request, env) {
  const body = await readJson(request);
  const wallet = String(body?.wallet || '');
  if (!WALLET_RE.test(wallet)) return errorJson(env, 'Invalid wallet', 400);

  const canonical = canonicalYouTubeUrl(String(body?.url || ''));
  if (!canonical) return errorJson(env, 'url must be a YouTube video link or id', 400);

  /* Everything that can be judged from the request alone is judged here,
     before any database read. A malformed amount is a 400 whatever the
     state of the catalogue, and checking it first means garbage costs us
     no queries — and, less obviously, that the caller gets told the real
     problem. When this lived below the already-live guard, asking for
     zero credits on a track you were already promoting answered "you
     already have a campaign", which is true but not the thing to fix. */

  /* No minimum. One credit = one person's attention, so one credit is a
     perfectly coherent (if small) campaign, and refusing it would only
     punish someone with little to spend. */
  const asked = Math.floor(Number(body?.credits ?? body?.tokens));
  if (!Number.isFinite(asked) || asked < 1) {
    return errorJson(env, 'Choose at least 1 credit', 400);
  }
  const spend = Math.min(asked, 100000);

  // 'popup', 'ai', or both. Unknown modes are dropped rather than rejected.
  const wanted = String(body?.modes || 'popup').split(',').map(s => s.trim().toLowerCase());
  const modes = ['popup', 'ai'].filter(m => wanted.includes(m));
  if (!modes.length) return errorJson(env, 'Choose at least one way to promote', 400);

  /* AI placement is matched on mood, so an AI campaign with no tags would
     be offered in no brief and quietly never spend a credit. Refusing it
     is kinder than taking the money: the owner finds out now rather than
     from a campaign that sits at full credits for a week.

     A campaign that is only after pop-up cards needs no tags. */
  const tags = parseTags(body?.tags);
  if (modes.includes('ai') && !tags.length) {
    return errorJson(env,
      'Pick at least one mood so the DJ knows which briefs this track suits',
      400, 'no_tags');
  }

  const track = await getTrackByUrl(env.DB, canonical);
  if (!track) return errorJson(env, 'That track is not in the catalogue yet', 404);
  if (track.verified === 0) {
    return errorJson(env, 'That track has not been confirmed playable yet', 409, 'unverified');
  }

  const now = nowIso();

  /* One live campaign per track per owner. Without this, promoting the
     same track twice created two rows that each received every event, so
     the numbers doubled and the owner was billed twice for one impression.
     A second attempt is a top-up, which is what the owner meant anyway. */
  const existing = await liveCampaignFor(env.DB, wallet, canonical, now);
  if (existing) {
    return errorJson(env,
      `You already have a live campaign for this track with ${existing.credits_remaining} credits left — add credits to it instead`,
      409, 'already_live');
  }

  const label = String(body?.label || track.name || '').trim().slice(0, 120);

  await ensureWallet(env.DB, wallet, now);
  const balance = await walletBalance(env.DB, wallet);
  if (balance < spend) {
    return errorJson(env, `Not enough riff tokens (need ${spend}, have ${balance})`, 402, 'poor');
  }

  await addLedger(env.DB, wallet, -spend, 'promote', canonical, now);
  const id = await addCampaign(env.DB, {
    wallet, url: canonical, name: track.name, label,
    modes: modes.join(','), credits: spend, now,
  });
  if (tags.length) await setCampaignTags(env.DB, id, tags.join(','));

  return json(env, {
    ok: true, id, label, modes, tags, credits: spend,
    balance: balance - spend,
  }, 201);
}

/**
 * GET /api/promotions — the live campaigns, for display only.
 *
 * Nothing here is billed. The Database panel's promoted strip and the
 * player's "is this track promoted" check both read this, and neither is
 * an impression. Billing happens in handlePromoNext and nowhere else.
 */
export async function handlePromotions(request, env) {
  const list = await livePromotions(env.DB, nowIso(), 20, 'popup');

  /* A whitelist, not a blacklist. The first version of this dropped
     credits_remaining and passed everything else through, which still
     published `tokens` — the total ever bought — alongside `views`, and
     remaining is just one minus the other, so the budget was public
     after all. Naming what goes out means a column added to the table
     later cannot leak by simply existing.

     `views` stays: it is how many times riffrolled showed the card, the
     promoted strip's badge displays it, and on its own it says nothing
     about what is left to spend. Budget — tokens, credits_remaining —
     is the owner's business and reaches them through
     /api/promotions/mine instead. */
  return json(env, list.map((p) => ({
    id: p.id, url: p.url, name: p.name, label: p.label, modes: p.modes,
    views: p.views, plays: p.plays, likes: p.likes,
    dislikes: p.dislikes, replays: p.replays,
  })));
}

/**
 * GET /api/promotions/next — one campaign to show, and a credit spent.
 *
 * This is the only endpoint that moves money, and it exists because the
 * browser used to do this job. `/api/promotions` returned the top twenty
 * and the pop-up ran the weighted lottery locally; the moment an
 * impression cost a credit, that let anyone drain a rival's campaign with
 * a loop against the reporting endpoint.
 *
 * Now the server picks, debits as it picks, and tells the client what to
 * draw. A credit spent means riffrolled showed the card — which is exactly
 * what one credit is sold as. Nothing the browser says can change a
 * balance.
 */
export async function handlePromoNext(request, env, url) {
  const now = nowIso();
  const mode = url.searchParams.get('mode') === 'ai' ? 'ai' : 'popup';
  const pool = await livePromotions(env.DB, now, 25, mode);
  if (!pool.length) return json(env, { ok: true, promotion: null });

  /* Weighted by credits remaining, so a bigger campaign is shown more
     often — the same lottery the client used to run, moved somewhere it
     can't be edited. `exclude` lets a client say "not this one again
     straight away" without that being able to force a particular result. */
  const skip = new Set(String(url.searchParams.get('exclude') || '')
    .split(',').map(Number).filter(Boolean));
  let choices = pool.filter((p) => !skip.has(p.id));
  if (!choices.length) choices = pool;

  const total = choices.reduce((n, p) => n + Math.max(1, p.credits_remaining), 0);
  let r = Math.random() * total;
  let pick = choices[choices.length - 1];
  for (const p of choices) { r -= Math.max(1, p.credits_remaining); if (r <= 0) { pick = p; break; } }

  /* The debit decides it. If two requests race for a campaign's last
     credit the second one's UPDATE matches nothing, and that request
     simply gets no ad rather than a free one. */
  const got = await spendCredit(env.DB, pick.id, now);
  if (!got) return json(env, { ok: true, promotion: null });

  return json(env, {
    ok: true,
    promotion: {
      id: pick.id, url: pick.url, name: pick.name, label: pick.label, modes: pick.modes,
    },
  }, 200, { 'Cache-Control': 'no-store' });
}

/**
 * POST /api/promo/event  { id | url, kind: 'play' | 'like' | 'dislike' | 'replay' }
 *
 * Engagement, not money. Since the serve now counts the impression and
 * spends the credit, this endpoint can no longer affect a balance however
 * often it is called — which is the only reason it is safe to leave
 * unauthenticated. `view` is rejected: an impression is something
 * riffrolled did, not something a browser may claim.
 */
export async function handlePromoEvent(request, env) {
  const body = await readJson(request);
  const kind = String(body?.kind || '');
  if (!['play', 'like', 'dislike', 'replay'].includes(kind)) {
    return errorJson(env, 'kind must be play, like, dislike or replay', 400);
  }

  const id = Number(body?.id);
  if (Number.isFinite(id) && id > 0) {
    return json(env, { ok: true, counted: await bumpCampaignStat(env.DB, id, kind) });
  }

  // by url: every live campaign for that track. One per owner, so this is
  // at most a handful of rows and each owner sees their own engagement.
  const canonical = canonicalYouTubeUrl(String(body?.url || ''));
  if (!canonical) return errorJson(env, 'An id or a YouTube url is required', 400);
  const live = await livePromotions(env.DB, nowIso(), 25, 'popup');
  let counted = 0;
  for (const p of live) if (p.url === canonical) { if (await bumpCampaignStat(env.DB, p.id, kind)) counted++; }
  return json(env, { ok: true, counted: counted > 0 });
}

/**
 * POST /api/promotions/brief  { brief_id, tags: [...] }
 *   → { promotions: [ { id, url, name, label, tags } ] }
 *
 * The AI surface. Nothing is charged here, because nothing has happened
 * yet: a brief that is built and never copied put no track in front of
 * anybody, and one credit is one person's attention.
 *
 * What it does do is write down which campaigns were in this brief. That
 * is the whole reason the claim call is safe — see the comment above
 * offerBriefCandidate in queries.js.
 */
export async function handleBriefOffers(request, env) {
  const body = await readJson(request);
  const briefId = String(body?.brief_id || '');
  if (!BRIEF_RE.test(briefId)) return errorJson(env, 'Invalid brief id', 400);

  const briefTags = parseTags(body?.tags);
  const cfg = await getConfig(env);
  const want = Math.max(0, Math.min(10, cfg.AI_CANDIDATES_PER_BRIEF));
  if (!want || !briefTags.length) return json(env, { ok: true, promotions: [] });

  const now = nowIso();
  const pool = await aiCampaignPool(env.DB, now);

  /* Ranked by fit, and a campaign that fits nothing is not offered at
     all. An untargeted placement is worth less than nothing to everyone
     involved: the promoter pays for a listener who was never going to
     care, and the listener's brief comes back with a track that does not
     belong in it. */
  const ranked = pool
    .map((p) => ({ p, score: tagScore(parseTags(p.tags), briefTags) }))
    .filter((x) => x.score > 0)
    .sort((a, b) => (b.score - a.score)
      || (b.p.credits_remaining - a.p.credits_remaining))
    .slice(0, want);

  for (const { p } of ranked) await offerBriefCandidate(env.DB, briefId, p.id, now);

  // unclaimed offers pile up from briefs nobody copied; swept on a sample
  // of requests rather than on a timer riffrolled does not have
  if (Math.random() < 0.04) await pruneBriefOffers(env.DB, now);

  return json(env, {
    ok: true,
    promotions: ranked.map(({ p }) => ({
      id: p.id, url: p.url, name: p.name, label: p.label, tags: parseTags(p.tags),
    })),
  }, 200, { 'Cache-Control': 'no-store' });
}

/**
 * POST /api/promotions/brief/claim  { brief_id }  → { charged }
 *
 * The billable moment. Dan's call, and the right one: the credit is spent
 * on COPY, not on import. Copying is the point at which the promoted
 * track has definitely been in front of a person — they have the brief in
 * their clipboard and they are about to hand it to an AI. Whether they
 * then import the result is a statistic about how well the placement
 * worked, not the thing being sold.
 *
 * Charging on import would also be charging for something riffrolled does
 * not control: an AI that silently drops the promoted track would mean
 * the promoter paid nothing for a placement that did happen, and the
 * listener's attention would have been spent for free.
 *
 * Copying the same brief twice charges once — that is the `charged = 0`
 * guard, and it is why the brief id exists at all.
 */
export async function handleBriefClaim(request, env) {
  const body = await readJson(request);
  const briefId = String(body?.brief_id || '');
  if (!BRIEF_RE.test(briefId)) return errorJson(env, 'Invalid brief id', 400);

  const now = nowIso();
  const owed = await unchargedOffers(env.DB, briefId);
  let charged = 0;

  for (const id of owed) {
    // claim first: the row is the lock, so a second claim for the same
    // brief finds nothing to take however fast it arrives
    if (!(await claimBriefOffer(env.DB, briefId, id))) continue;
    /* If the campaign has run dry since it was offered, the placement
       still happened — the track is in the brief the person just copied.
       There is simply nothing left to take, and inventing a credit to
       take would be worse than logging it. Same call as the pop-up card
       suppressed by ytGuard after its credit was spent. */
    if (await spendCredit(env.DB, id, now)) charged++;
  }

  return json(env, { ok: true, charged, offered: owed.length });
}

/** GET /api/promotions/mine?wallet=… — the caller's own promotions + stats. */
export async function handleMyPromotions(request, env, url) {
  const wallet = String(url.searchParams.get('wallet') || '');
  if (!WALLET_RE.test(wallet)) return errorJson(env, 'Invalid wallet', 400);
  const list = await walletPromotions(env.DB, wallet, nowIso(), 25);
  return json(env, list);
}

/**
 * POST /api/promotion/action  { wallet, id, action: 'pause'|'resume'|'extend', credits? }
 *
 * Pause and resume are now trivial: credits don't drain while a campaign
 * is paused because nothing is being served, so there is no clock to bank
 * and no time to lose. That is the quiet win in switching from selling
 * hours to selling attention — a promoter can hold their spend for a
 * better moment at no cost, and the code that used to juggle remaining_ms
 * goes away.
 */
export async function handlePromotionAction(request, env) {
  const body = await readJson(request);
  const wallet = String(body?.wallet || '');
  const id = Number(body?.id);
  const action = String(body?.action || '');
  if (!WALLET_RE.test(wallet)) return errorJson(env, 'Invalid wallet', 400);
  if (!Number.isInteger(id) || id <= 0) return errorJson(env, 'Invalid promotion id', 400);

  const promo = await getOwnedPromotion(env.DB, id, wallet);
  if (!promo) return errorJson(env, 'Campaign not found', 404);
  const now = nowIso();

  if (action === 'pause') {
    if (promo.paused) return errorJson(env, 'Already paused', 400);
    await pausePromotion(env.DB, id, 0);
    return json(env, { ok: true, paused: true, credits_remaining: promo.credits_remaining });
  }

  if (action === 'resume') {
    if (!promo.paused) return errorJson(env, 'Not paused', 400);
    if (promo.credits_remaining <= 0) return errorJson(env, 'No credits left — add some first', 400);
    await resumePromotion(env.DB, id, '');
    return json(env, { ok: true, paused: false, credits_remaining: promo.credits_remaining });
  }

  if (action === 'extend') {
    const add = Math.floor(Number(body?.credits ?? body?.tokens) || 0);
    if (!(add > 0)) return errorJson(env, 'Credits to add must be a positive number', 400);
    if (add > 100000) return errorJson(env, 'That is more than the per-top-up limit', 400);

    const balance = await walletBalance(env.DB, wallet);
    if (balance < add) {
      return errorJson(env, `Not enough riff tokens (need ${add}, have ${balance})`, 402, 'poor');
    }
    await addLedger(env.DB, wallet, -add, 'promote_extend', String(promo.url), now);
    await addCredits(env.DB, id, add);
    return json(env, {
      ok: true, added: add, balance: balance - add,
      credits_remaining: promo.credits_remaining + add,
    });
  }

  return errorJson(env, "action must be 'pause', 'resume' or 'extend'", 400);
}
